# MENU
1.	Multiplication of two given matrixes 
2.	Sum of the diagonal elements of a given Matrix 
3.	Element-wise Matrix Multiplication (Hadamard Product)
4.	Outer product of two given vectors
5.	Determinant of a given square matrix

Additional set of exercises:

1.	Write a program to find the maximum and minimum from a given vector. Your implementation should be computationally efficient. 
2.	Can we think of a program to find all linearly independent vectors from a set of N, d-dimensional vectors?


# Functions

In [1]:
import numpy as np
import sympy

In [2]:
a = [[1,2],[3,4]]
b = [[1,2],[3,4]]

In [3]:
def transpose(mat):
    return [[mat[j][i] for j in range(len(mat))] for i in range(len(mat[0]))]

In [4]:
def matrix_multiplication(mat1,mat2):
    if len(mat1[0])!=len(mat2):
        raise Exception("Matrices can't be multiplied")
    else:
        mat2 = transpose(mat2)
        mat = list()
        for i in range(len(mat1)):
            mat.append([sum(list(map(lambda a,b:a*b,mat1[i],mat2[j]))) for j in range(len(mat2))])
        return mat                

In [5]:
def trace(mat):
    if len(mat[0]) != len(mat):
        raise Exception("Enter a square matrix")
    else:
        return sum([mat[i][i] for i in range(len(mat))])

In [6]:
def hadamard_product(mat1,mat2):
    if len(mat1) != len(mat2) or len(mat1[0]) != len(mat2[0]):
        raise Exception("Matrices can't be multiplied")
    else:
        return [list(map(lambda a,b:a*b,mat1[i],mat2[i])) for i in range(len(mat1))]

In [7]:
def outer_vector(v1,v2):
    return [[v1[i]*v2[j] for j in range(len(v2))] for i in range(len(v1))]

In [8]:
def min_max(v):
    n = len(v)
    a = 0
    if not n % 2:
        minimum = min(v[0],v[1])
        maximum = max(v[0],v[1])
        a = 2  
    else:
        minimum = maximum = v[0]
        a = 1

    for i in range(a,n,2):
        if( v[i] > v[i+1]):
            minimum = min(minimum,v[i+1])
            maximum = max(v[i],maximum)
        else:
            minimum = min(v[i],minimum)
            maximum = max(maximum,v[i+1])
    return minimum, maximum

# RUN

In [9]:
print("1. Multiplication of given matrixes :",matrix_multiplication(a,b))
print("\n2. Trace of given matrix A :\t",trace(a))
print("   Trace of given matrix A :\t",trace(b))
print("\n3. Element-wise Matrix Multiplication (Hadamard Product) :",hadamard_product(a,b))
print("\n4. Outer Product :",outer_vector([7,3,2,1],[3,2,1]))
print("\n5. Determinant of matrix A :\t",round(np.linalg.det(a)))
print("   Determinant of matrix B :\t",round(np.linalg.det(b)))

1. Multiplication of given matrixes : [[7, 10], [15, 22]]

2. Trace of given matrix A :	 5
   Trace of given matrix A :	 5

3. Element-wise Matrix Multiplication (Hadamard Product) : [[1, 4], [9, 16]]

4. Outer Product : [[21, 14, 7], [9, 6, 3], [6, 4, 2], [3, 2, 1]]

5. Determinant of matrix A :	 -2.0
   Determinant of matrix B :	 -2.0


## Additional questions

In [10]:
vec = list([1, 2, 3, 4, 5])
minmax = min_max(vec)
print("Min in the given vector: ",minmax[0])
print("Max in the given vector: ",minmax[1])

Min in the given vector:  1
Max in the given vector:  5


In [11]:
matrix = np.array(
    [
        [1, 0, 0, 1],
        [0, 1 ,0 ,0],
        [0, 0, 1, 0],
        [0, 1, 1, 0],
    ])

red_matrix, inds = sympy.Matrix(matrix).T.rref()

In [12]:
print("Independent vectors")
for i in inds:
    print(matrix[i])

Independent vectors
[1 0 0 1]
[0 1 0 0]
[0 0 1 0]
